In [1]:
#Main imports
import pytest
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import networkx as nx

from typing import Tuple

import pytorch_lightning as pl
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import nn, optim
from torch.autograd import Variable

from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.metrics import precision_score, recall_score, roc_auc_score
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification

from xgboost import XGBClassifier

from sklearn.utils._testing import ignore_warnings
from sklearn.exceptions import ConvergenceWarning

import os.path

In [2]:
#Add files to sys 
import os, sys
sys.path.append(os.getcwd())

## DECAF Model

In [4]:
from tests.utils import load_adult
from tests.test_decaf import test_run_experiments

X, y, df = load_adult()

ModuleNotFoundError: No module named 'decaf'

In [4]:
test_run_experiments(X, y, df, 'ftu')

C:\Users\space\anaconda3\envs\factai\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
C:\Users\space\anaconda3\envs\factai\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:99: UserWarning: you passed in a val_dataloader but have no validation_step. Skipping val loop
  rank_zero_warn(f"you passed in a {loader_name} but have no {step_name}. Skipping {stage} loop")

  | Name          | Type             | Params
---------------------------------------------------
0 | generator     | Generator_causal | 128 K 
1 | discriminator | Discriminator    | 43.4 K
---------------------------------------------------
171 K     Trainable params
196       Non-trainable params
171 K     Total param

baseline scores 0.8771004942339374 0.9400547364703805 0.7713060043566607
Initialised adjacency matrix as parsed:
 Parameter containing:
tensor([[0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      

C:\Users\space\anaconda3\envs\factai\lib\site-packages\pytorch_lightning\trainer\data_loading.py:106: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."


Training: -1it [00:00, ?it/s]

[[4.35769320e-01 3.29245928e-08 1.41432852e-01 ... 5.98687939e-06
  4.58957881e-01 5.24330745e-10]
 [4.25009340e-01 1.68820694e-10 1.65413752e-01 ... 7.41137512e-07
  4.73381132e-01 1.29614534e-07]
 [1.21706419e-01 4.57931459e-01 2.29698718e-01 ... 5.53579768e-04
  4.58740830e-01 2.02330062e-03]
 ...
 [3.93053889e-01 6.31911278e-01 2.39255965e-01 ... 1.07838621e-03
  4.63055521e-01 3.52310570e-10]
 [4.46874164e-02 1.33586378e-10 1.42350972e-01 ... 7.38972332e-04
  4.72407132e-01 7.09834918e-02]
 [4.35627908e-01 4.49071944e-01 1.03305906e-01 ... 5.95281762e-08
  4.60556477e-01 2.76018138e-04]]
Getting metrics...
0        1.000000
1        1.000000
2        1.000000
3        1.000000
4        1.000000
           ...   
30157    1.000000
30158    0.000517
30159    1.000000
30160    1.000000
30161    0.000484
Name: sex, Length: 30162, dtype: float32
Statistics for dataset for mode: ftu
Precision: 0.9378238341968912
Recall: 0.7941928345224922
AUROC: 0.722545443317406
FTU: 0.2851932895696571

TypeError: 'NoneType' object is not iterable

In [5]:
test_run_experiments(X, y, df, 'dp')

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
C:\Users\space\anaconda3\envs\factai\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:99: UserWarning: you passed in a val_dataloader but have no validation_step. Skipping val loop
  rank_zero_warn(f"you passed in a {loader_name} but have no {step_name}. Skipping {stage} loop")

  | Name          | Type             | Params
---------------------------------------------------
0 | generator     | Generator_causal | 128 K 
1 | discriminator | Discriminator    | 43.4 K
---------------------------------------------------
171 K     Trainable params
196       Non-trainable params
171 K     Total params
0.686     Total estimated model params size (MB)


baseline scores 0.887231223015432 0.9161737441511433 0.7824075966360404
Initialised adjacency matrix as parsed:
 Parameter containing:
tensor([[0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       

C:\Users\space\anaconda3\envs\factai\lib\site-packages\pytorch_lightning\trainer\data_loading.py:106: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."


Training: -1it [00:00, ?it/s]

[[3.7089515e-01 9.1037269e-05 3.4088053e-02 ... 1.7860682e-05
  4.4294679e-01 1.7703438e-07]
 [1.3247526e-01 2.4755055e-01 1.6436018e-01 ... 7.4902329e-07
  4.2556778e-01 8.0773279e-06]
 [3.6864707e-01 6.8531078e-01 7.8647874e-02 ... 4.3885182e-03
  3.7024042e-01 5.2202722e-07]
 ...
 [3.7543008e-01 2.8371427e-04 1.6452190e-01 ... 9.5931694e-02
  4.2484123e-01 2.8253990e-07]
 [2.4851978e-02 2.0432137e-06 1.2642306e-01 ... 1.4537807e-07
  4.2815462e-01 2.8388336e-02]
 [2.3136160e-01 6.3227927e-03 8.9605026e-02 ... 3.2656683e-06
  4.3474653e-01 1.6616696e-01]]
Getting metrics...
0        0.000176
1        1.000000
2        0.000163
3        1.000000
4        0.977284
           ...   
30157    1.000000
30158    1.000000
30159    0.939802
30160    1.000000
30161    0.999971
Name: sex, Length: 30162, dtype: float32
Statistics for dataset for mode: dp
Precision: 0.9620091702002965
Recall: 0.9682176190971861
AUROC: 0.5732214120840143
FTU: 0.045951859956236324
DP: 0.055407565263718594


In [6]:
test_run_experiments(X, y, df, 'cf')

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
C:\Users\space\anaconda3\envs\factai\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:99: UserWarning: you passed in a val_dataloader but have no validation_step. Skipping val loop
  rank_zero_warn(f"you passed in a {loader_name} but have no {step_name}. Skipping {stage} loop")

  | Name          | Type             | Params
---------------------------------------------------
0 | generator     | Generator_causal | 128 K 
1 | discriminator | Discriminator    | 43.4 K
---------------------------------------------------
171 K     Trainable params
196       Non-trainable params
171 K     Total params
0.686     Total estimated model params size (MB)


baseline scores 0.8823899371069183 0.9289750154498102 0.7776867618538342
Initialised adjacency matrix as parsed:
 Parameter containing:
tensor([[0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      

C:\Users\space\anaconda3\envs\factai\lib\site-packages\pytorch_lightning\trainer\data_loading.py:106: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."


Training: -1it [00:00, ?it/s]

[[4.1337845e-01 8.4799504e-01 2.5292290e-02 ... 2.7983971e-08
  4.8152587e-01 5.8112843e-08]
 [4.2829132e-01 7.4742770e-01 7.1436688e-02 ... 1.2096819e-02
  4.7435984e-01 2.9705085e-03]
 [4.0756512e-01 3.6773622e-09 1.8982632e-01 ... 1.4494367e-05
  4.7812492e-01 1.9173013e-08]
 ...
 [4.5078513e-01 1.9508073e-01 1.7670873e-01 ... 3.1376153e-02
  4.7585717e-01 6.6416787e-06]
 [4.0702873e-01 1.0020887e-06 9.2037201e-02 ... 1.6135353e-08
  4.7107500e-01 1.0830268e-02]
 [4.1281366e-01 1.6692541e-11 1.2309223e-01 ... 3.5746716e-06
  4.8081869e-01 2.8868322e-04]]
Getting metrics...
0        0.000414
1        0.000308
2        1.000000
3        1.000000
4        1.000000
           ...   
30157    0.000422
30158    1.000000
30159    1.000000
30160    0.999999
30161    0.000247
Name: sex, Length: 30162, dtype: float32
Statistics for dataset for mode: cf
Precision: 0.8317031928649581
Recall: 0.9999601371282787
AUROC: 0.49998006856413935
FTU: 0.0043432133147669255
DP: 0.00013319126265320946


# CTGAN - COMPARISON TO DECAF
This model will automatically load pretrained models and calculate the appropriate metrics.
It will also print the progress. (This will still take some time!) These tests will output the approximate metrics.

NOTE: THIS WILL TAKE SIGNIFICANT TIME EVEN WITH SAVED MODELS AS THE SAMPLING TAKES TIME TOO

In [ ]:
from table_evaluator import TableEvaluator
from ctgan import CTGANSynthesizer

In [ ]:
%run ./CTGAN/FACT_GAN.ipynb

# Run the experiments with the three privacy definitions
run_experiment_CTGAN('FTU')
run_experiment_CTGAN('CF') 
run_experiment_CTGAN('DP')